### ISSUE TITLE
Underscore prefix on long attachment names

### ISSUE THREAD

**Issue by hm122** [nette/mail#24]
When I am using long names for mail attachments, the attachment name starts with an underscore, even though I did not set an underscore:

`Content-Type: text/plain; name="_XXXXXXX_YYYYYYY_ZZZZZZZ_123456789.csv"
Content-Transfer-Encoding: quoted-printable
Content-Disposition: attachment;filename="_XXXXXXX_YYYYYYY_ZZZZZZZ_123456789.csv"`

Do you know what might cause this problem?

**Comment by milo** [comment]
What contains the `$file` when you add it by `addAttachment()`? The name is sanitized [here](https://github.com/nette/mail/blob/e53945342a4c765b91a7e3950e554e1c3d702f08/src/Mail/Message.php#L327).

**Comment by hm122** [comment]
I have found out that this problem also depends on the mail client. The original email source looks like this:
Content-Disposition:` attachment; filename="
	Filename_debug_customer_date_20160322_114204.csv"

While the file is correctly displayed in thunderbird, Outlook shows the file as "_Filename_debug_customer_date_20160322_114204.csv".

The file contains simple csv text data, the filename is set exactly as above, but without newline or spaces in front. 

Following another example of the source with an empty file attached:

**Short name:**
Content-Type: application/x-empty
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="foobar.csv"

**Long name:**
Content-Type: application/x-empty
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="
	foobar_foobar_foobar_foobar_foobar_foobar_foobar_foobar_.csv"

**Comment by xsuchy09** [comment]
I can confirm this bug. For example PDF software is opening PDF file as attachment with `%09` at the beginning of the filename - because of tab which is added in `MimePart:append` called from `MimePart:encodeHeader` which is called from `MimePart:getEncodedHeader`. When file is saving Ubuntu save it with `-` at the beginning. Attachment is added like:
```
Content-Disposition: attachment; filename="
	invoice-7lQYGxp6er2Dpb28ZdDvPOoML.pdf"
```
Solution is to add it like:
```
Content-Disposition: attachment; filename=
	"invoice-7lQYGxp6er2Dpb28ZdDvPOoML.pdf"
```
or don't fold header lines which is not specified in RFC. It is just good use case for terminal clients ofc.

More info in czech language:
https://forum.nette.org/cs/31371-email-prilozeny-soubor-a-podivne-09-pred-nazvem-souboru#p208896

**Comment by dg** [comment]
@xsuchy09 Thanks for the analysis and solution.
