### ISSUE TITLE
 fwrite(): SSL: Broken pipe    

### ISSUE THREAD

**Issue by aoxiang594** [nette/mail#50]
Hello Developer，Thank you for developing tools that surprised me so much，It really makes me feel particularly easy and convenient.

but  i have a problem ,when i send attachment with mail,

It occasionally tells me this happened    fwrite(): SSL: Broken pipe       
I checked this question and I found that this error is bound to occur whenever I send a larger attachment

Can you help me to fix  this problem? thank you very much

------------------------------------------------------------------------------------------------
[2018-04-13 09:43:34]:size:16.453886032104

                                    
  [think\exception\ErrorException]  
  fwrite(): SSL: Broken pipe        
                                    

Exception trace:
 () at /data/www/screenWeb/vendor/nette/mail/src/Mail/SmtpMailer.php:195
 think\Error::appError() at n/a:n/a
 fwrite() at /data/www/screenWeb/vendor/nette/mail/src/Mail/SmtpMailer.php:195
 Nette\Mail\SmtpMailer->write() at /data/www/screenWeb/vendor/nette/mail/src/Mail/SmtpMailer.php:111
 Nette\Mail\SmtpMailer->send() at /data/www/screenWeb/application/common/logic/MailLogic.php:50
 app\common\logic\MailLogic->sendMail() at /data/www/screenWeb/application/spider/controller/Push.php:100

**Comment by milo** [comment]
The `broken pipe` is a TCP protocol message and happens when you are trying to write into stream, but remote site already closed the connection and didn't inform your site (client).

I can imagine that this is a result of some remote mail server restriction according to mail size. IMHO, nothing to do it as a client. If you can, browse the remote mail server log to confirm this theory.
